export class CharacterInfo {
    id: number;
    name: string;
    description: string;
    img_src: string;
    favorited: boolean;
}

export var mockChars : CharacterInfo[] = [
    { id:0, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:1, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:2, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:3, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:4, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:5, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:6, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:7, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:8, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:9, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:10, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:11, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:12, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:13, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:14, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:15, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:16, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:17, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:18, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:19, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:20, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:21, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:22, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:23, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:24, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:25, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:26, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:27, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:28, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:29, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:30, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:31, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:32, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:33, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:34, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:35, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:36, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:37, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:38, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:39, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:40, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:41, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:42, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:43, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:44, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:45, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:46, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:47, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:48, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:49, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:50, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:51, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:52, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:53, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:54, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:55, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:56, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:57, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:58, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:59, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:60, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:61, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:62, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:63, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:64, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:65, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:66, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:67, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:68, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:69, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:70, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:71, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:72, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:73, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:74, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:75, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:76, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:77, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:78, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:79, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:80, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:81, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:82, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:83, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:84, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:85, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:86, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:87, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:88, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:89, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:90, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:91, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:92, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:93, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:94, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:95, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:96, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:97, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:98, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:99, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:100, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:101, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:102, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:103, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:104, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:105, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:106, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:107, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:108, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:109, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:110, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:111, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:112, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:113, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:114, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:115, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:116, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:117, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:118, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:119, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:120, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:121, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:122, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:123, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:124, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:125, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { id:126, favorited:false, name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { id:127, favorited:false, name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { id:128, favorited:false, name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { id:129, favorited:false, name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { id:130, favorited:false, name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { id:131, favorited:false, name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { id:132, favorited:false, name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { id:133, favorited:false, name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { id:134, favorited:false, name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },

]
