export class CharacterInfo {
    name : string;
    //realName: string;
    description: string;
    img_src: string;
    //favorited: boolean;
}

export var mockChars : CharacterInfo[] = [
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },
    { name:'Captain Marvel', description: 'Her description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg' },
    { name:'Deadpool', description: 'Deadpool description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_xlarge.jpg' },
    { name:'Black Panther', description: 'Wakanda king description', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_xlarge.jpg' },
    { name:'Jessica Jones', description: 'Jessica Jones description text', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/b/40/jessica.jpg' },
    { name:'Spider-Man', description: "Neighbourhood's friend", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' },
    { name:'Ant-man', description: "Ant-man description text", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_xlarge.jpg' },
    { name:'Iron Man', description: 'Self-described as Genius, Billionaire, Playboy, Philanthrope', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/6/a0/55b6a25e654e6/standard_xlarge.jpg' },
    { name:'Wolverine', description: 'Description for Captain America', img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_xlarge.jpg' },
    { name:'Luke Cage', description: "Luke Cage description", img_src: 'https://i.annihil.us/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_xlarge.jpg' },

]